name:                firebase-admin
version:             0.1.0.0
github:              "githubuser/firebase-admin"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/firebase-admin#readme>

dependencies:
- base >= 4.7 && < 5
- gogol
- gogol-core
- unordered-containers
- scientific
- exceptions
- bytestring
- time
- jose
- transformers
- http-conduit
- aeson
- http-types
- http-client
- lens
- mtl
- containers

library:
  source-dirs: src

executables:
  firebase-admin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - firebase-admin

tests:
  firebase-admin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - firebase-admin
